### ISSUE TITLE
Andamento do Projeto

### ISSUE THREAD

**Issue by sialka** [NathanPerote/AppFinancas#2]
**Status Geral**
- [x] Criar Repositório GIT
- [ ] Subir documentos do Projeto Fase 1
- [ ] Criar conta na AWS
- [ ] Configurar a Conta E2
- [ ] Fase 1

**Documentos Fase 1**
- [x] Subir documentos ref. ao projeto

**Fase 1**
- [ ] Subir API 
- [ ] Receber dados do POST
- [ ] Gravar dados no banco
- [ ] Devolver JSON com (IR, Ganho, Gasto, Líquido, IR Total, IR Devido)
- [ ] Devolver JSON com dados Mensal

**Comment by NathanPerote** [comment]
Obrigado
